# $Id: Makefile.ultrix,v 1.5 2003/05/20 00:27:56 n8gray Exp $
CC=cc
AR=ar
#
# To evaluate an alternative layout for the Replace/Find dialog, add
# -DREPLACE_SCOPE to the CFLAGS. See the README file for more information.
#
# To test if the Motif library exports the runtime version
# add -DHAVE__XMVERSIONSTRING to CFLAGS
#
CFLAGS=-O -DUSE_MOTIF_GLOB
ARFLAGS=-urs
BIGGER_STRINGS= -Wf,-XNl8192
LIBS=-lm -lXm -lXt -lX11

include Makefile.common

verify_config:
